rly_file = "Worcester_Region.rly"
ttb_files = [ "Worcester_Region_Mar_2025_0600.ttb",]
img_files = [ "Worcester_Region.bmp",]
doc_files = [ "README.md",]
ssn_files = [ "Worcester_Region_Mar_2025_0600.ssn",]
release_date = "2026-02-01"
version = "1.1.0"
country_code = "GB"
difficulty = 8
factual = true
description = "Simulation of the area around Worcester, UK"
year = 2025
display_name = "Worcester Region"
name = "Worcester Region"
signal_position = "left"
author = "Krizar"
contributors = []
